image: ubuntu:22.04

stages:
  - test

variables:
  DEBIAN_FRONTEND: noninteractive

.test_setup:
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends build-essential gcc make

unit-test:
  extends: .test_setup
  stage: test
  script:
    - make test

integration-test:
  extends: .test_setup
  stage: test
  script:
    - make integration-test

asan:
  extends: .test_setup
  stage: test
  script:
    - make sanitize

tsan:
  extends: .test_setup
  stage: test
  script:
    - make tsan
