#ifndef STREAM_CONFIG_H
#define STREAM_CONFIG_H

#include "circular_buffer.h"

#define PKG_SIZE       188u
#define PACKAGES_PER_DECODE_BLOCK  4u
#define PACKAGES_PER_ENCODE_BLOCK  8u

#define DECODE_BLOCK   (PKG_SIZE * PACKAGES_PER_DECODE_BLOCK)
#define ENCODE_BLOCK   (PKG_SIZE * PACKAGES_PER_ENCODE_BLOCK)

#define BUFFER_BLOCK_COUNT  16u
#define BUFFER_BLOCK_SIZE   1024u
#define BUFFER_OVERFLOW_POLICY  CB_OVERFLOW_OVERWRITE

#define MF_MAX_FLOWS        8u
#define MF_QUEUE_CAPACITY   32u
#define MF_MIXED_CAPACITY   64u

#endif /* STREAM_CONFIG_H */
