#ifndef STREAM_CONFIG_H
#define STREAM_CONFIG_H

#include "circular_buffer.h"

#define PKG_SIZE       188u
#define PACKAGES_PER_DECODE_BLOCK  4u
#define PACKAGES_PER_ENCODE_BLOCK  8u
#define XOR_FEC_PARITY_SHARDS      1u

#define DECODE_BLOCK   (PKG_SIZE * PACKAGES_PER_DECODE_BLOCK)
#define ENCODE_BLOCK   (PKG_SIZE * PACKAGES_PER_ENCODE_BLOCK)
#define XOR_FEC_ENCODE_BLOCK (DECODE_BLOCK + (PKG_SIZE * XOR_FEC_PARITY_SHARDS))
#define CODEC_MAX_ENCODE_BLOCK ENCODE_BLOCK

#define BUFFER_BLOCK_COUNT  2048u
#define BUFFER_BLOCK_SIZE   1024u
#define BUFFER_OVERFLOW_POLICY  CB_OVERFLOW_REJECT

#define MF_MAX_FLOWS        8u
#define MF_QUEUE_CAPACITY   2048u
#define MF_MIXED_CAPACITY   4096u

#endif /* STREAM_CONFIG_H */
